### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by q1134269149** [tszalay/poisson#11]
Hi,
I run the command of poreseq after installed, but the following error occurred:
'''
(base) [qinh@node29 ~]$ poreseq
Traceback (most recent call last):
  File "/home/qinh/.local/bin/poreseq", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/qinh/anaconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/qinh/anaconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/qinh/anaconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/qinh/anaconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/qinh/anaconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/qinh/anaconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'poreseq' distribution was not found and is required by the application
'''
Can you give me some advice? Thanks

**Comment by q1134269149** [comment]
I solved this problem. I forgot install the numpy pkg. Thanks!
