### ISSUE TITLE
Installation error: No module named 'LoadData'

### ISSUE THREAD

**Issue by pvap3** [tszalay/poisson#12]
Hello,
I am trying to run poreseq but i am getting following error,

Traceback (most recent call last):
  File "/home/iob/.local/bin/poreseq", line 11, in <module>
    load_entry_point('poreseq', 'console_scripts', 'poreseq')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/iob/Downloads/poreseq/poreseq/__init__.py", line 1, in <module>
    from LoadData import LoadAlignedEvents
ModuleNotFoundError: No module named 'LoadData'

Help will be really appreciated.

**Comment by tszalay** [comment]
Hi, I'm sorry, I'm not sure what I can tell you here. This tool has been superseded by a number of better options in the last 5-6 years, and I'm not even sure it's able to run anymore. It looks like it's probably a python 2 - python 3 problem, but I'm not entirely sure about that. Realistically I should probably remove it from the package repository entirely, but I would highly recommend you try to find a more recent tool for error correcting nanopore data.

**Comment by pvap3** [comment]
Thank you so much for such nice and clear response.
Can you suggest me any tools?

**Comment by tszalay** [comment]
I'm not really sure, I haven't worked with nanopore sequencing data in almost six years, long enough that all of the tools since then are completely different. I would suggest looking for a recent review article or contacting someone still in the field. Good luck!

**Comment by pvap3** [comment]
Thank you.
